### ISSUE TITLE
nano1 장비에 tf serving을 통해 모델들이 작동하는지 확인하기

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/tfserving-inference#17]
- [x] mobilenet v1
- [x] mobilenet v2

메모리 부족으로 인해 로드 불가
~- [ ] inception v3~
~- [ ] yolo v5~
~- [ ] nlp~

**Comment by kh3654po** [comment]
- test 결과
    - 요청 100개를 병렬처리
    - 각 요청은 쓰레드로 처리되는데 이 쓰레드는 master 장비에서 생성되며 각 장비에 tf serving 요청을 보내고 결과를 받는 작업을 수행함
    - 쓰레드가 완료된 시간을 측정하고 결과로 보여주는 것이므로 추론시간에 더해 요청 보내고 받기까지의 시간도 포함됨
    - mobilenet v1
        
        avg: 1.874239010810852
        min: 0.12983298301696777
        max: 3.1880788803100586
        
    - mobilenet v2
        
        avg: 1.8070754170417787
        min: 0.23207879066467285
        max: 3.0405852794647217

inception v3는 메모리 부족으로 추론이 되지않음
추론 요청을 했을때
```
Traceback (most recent call last):
  File "/home/master/tfserving-inference/bench/run_grpc_bench.py", line 6, in <module>
    result = grpc_bench.run_bench(variables.num_tasks, variables.grpc_server_address, variables.use_https)
  File "/home/master/tfserving-inference/bench/inception_v3/grpc_bench.py", line 38, in run_bench
    result, thread_elapsed_time  = future.result()
  File "/home/master/.pyenv/versions/3.9.16/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/master/.pyenv/versions/3.9.16/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/master/.pyenv/versions/3.9.16/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/master/tfserving-inference/bench/inception_v3/grpc_bench.py", line 33, in <lambda>
    futures = [executor.submit(lambda: module_grpc.predict(stub, request)) for _ in range(num_tasks)]
  File "/home/master/tfserving-inference/bench/module/module_grpc.py", line 23, in predict
    result = stub.Predict(request, timeout=100.0)
  File "/home/master/.pyenv/versions/3.9.16/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/master/.pyenv/versions/3.9.16/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Error received from peer nvidia-nano1:8500 {created_time:"2023-04-06T03:25:52.021839526+09:00", grpc_status:4, grpc_message:"Deadline Exceeded"}"
```
위 에러가 나오는데 설정된 제한시간안에 추론을 다하지 못해서 나오는 에러이고 계속해서 요청하면 컨테이너가 종료됨

**Comment by hyu-leeky** [comment]
오케이. 석현아. Inception v3 가 처리되지 않는건 충분히 이해가 된다. 하나씩 워크로드를 완성해서 논문을 같이 작성해보자.

**Comment by kh3654po** [comment]
yolo v5를 nano 장비에서 테스트한 결과 inception v3와 마찬가지로 모델을 로드하는것까지는 완료가 되었지만 메모리 부족으로 인한 타임초과로 실패했습니다.

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/54831356/230781238-6c5bb9fc-079f-4851-a724-0639651bffe9.png">
메모리 사용량을 확인해본 결과 입니다.

**Comment by kh3654po** [comment]
nano1에서 nlp 모델은 메모리 부족으로 로드가 되지않았습니다.
